blueprint:
  name: Scheduled Outlet
  description: >
    **Version: 1.1.0**
    
    Turns a switch ON and OFF based on two time schedules.
    Each schedule includes:
      - Month-day start and end (e.g., 05-01 to 09-30)
      - Days of the week
      - Off and on times

    The outlet defaults to ON and will turn OFF only during active timer windows.

    On Home Assistant restart, after a 5-minute delay, it will check and restore the correct state.

    Optional temperature guardrails:
      - Provide a temperature sensor and choose whether to turn ON when above or below a threshold.
      - Separate ON and OFF thresholds create a hysteresis window to reduce rapid toggling.
      - Select Fahrenheit or Celsius; values auto-convert if the sensor reports the opposite unit.
  domain: automation
  input:
    outlet:
      name: Outlet Switch
      description: "The switch or smart outlet you want to control."
      selector:
        entity:
          domain: switch

    # --- Time Set 1 ---
    set1_start_md:
      name: Set 1 - Start (MM-DD)
      description: "Start of the first schedule (format: MM-DD, e.g., 05-01)."
      selector:
        text:
    set1_end_md:
      name: Set 1 - End (MM-DD)
      description: "End of the first schedule (format: MM-DD, e.g., 09-30)."
      selector:
        text:
    set1_days:
      name: Set 1 - Days of Week
      description: "Days of the week the first schedule is active."
      selector:
        select:
          options:
            - Monday
            - Tuesday
            - Wednesday
            - Thursday
            - Friday
            - Saturday
            - Sunday
          multiple: true
    set1_off_time:
      name: Set 1 - Turn OFF Time
      description: "Time to turn OFF the outlet for the first schedule."
      selector:
        time:
    set1_on_time:
      name: Set 1 - Turn ON Time
      description: "Time to turn ON the outlet for the first schedule."
      selector:
        time:

    # --- Time Set 2 ---
    set2_start_md:
      name: Set 2 - Start (MM-DD)
      description: "Start of the second schedule (format: MM-DD, e.g., 10-01)."
      selector:
        text:
    set2_end_md:
      name: Set 2 - End (MM-DD)
      description: "End of the second schedule (format: MM-DD, e.g., 04-30)."
      selector:
        text:
    set2_days:
      name: Set 2 - Days of Week
      description: "Days of the week the second schedule is active."
      selector:
        select:
          options:
            - Monday
            - Tuesday
            - Wednesday
            - Thursday
            - Friday
            - Saturday
            - Sunday
          multiple: true
    set2_off_time:
      name: Set 2 - Turn OFF Time
      description: "Time to turn OFF the outlet for the second schedule."
      selector:
        time:
    set2_on_time:
      name: Set 2 - Turn ON Time
      description: "Time to turn ON the outlet for the second schedule."
      selector:
        time:

    # --- Optional Temperature Control ---
    temperature_sensor:
      name: Temperature Sensor (optional)
      description: "Temperature sensor to guard the outlet. Leave empty to rely on schedule only."
      default: null
      selector:
        entity:
          domain: sensor
          device_class: temperature
    temperature_unit:
      name: Temperature Unit
      description: "Unit for the thresholds; the sensor reading will auto-convert if needed."
      default: Fahrenheit
      selector:
        select:
          options:
            - label: Fahrenheit (°F)
              value: Fahrenheit
            - label: Celsius (°C)
              value: Celsius
    temperature_mode:
      name: Temperature Mode
      description: "Choose whether high or low temperatures should turn the outlet ON."
      default: above
      selector:
        select:
          options:
            - label: Turn ON when temperature is ABOVE the ON threshold
              value: above
            - label: Turn ON when temperature is BELOW the ON threshold
              value: below
    temperature_on_threshold:
      name: Temperature ON Threshold
      description: "Temperature at which to turn ON (per the selected mode)."
      default: 75
      selector:
        number:
          min: -50
          max: 150
          step: 0.5
          unit_of_measurement: "°"
    temperature_off_threshold:
      name: Temperature OFF Threshold
      description: "Temperature at which to turn OFF (per the selected mode). Set to create a hysteresis gap."
      default: 72
      selector:
        number:
          min: -50
          max: 150
          step: 0.5
          unit_of_measurement: "°"

trigger:
  - platform: time
    at: !input set1_off_time
    id: set1_off

  - platform: time
    at: !input set1_on_time
    id: set1_on

  - platform: time
    at: !input set2_off_time
    id: set2_off

  - platform: time
    at: !input set2_on_time
    id: set2_on

  - platform: homeassistant
    event: start
    id: startup

  - platform: time_pattern
    minutes: "/5"
    id: periodic_check

variables:
  set1_start_md: !input set1_start_md
  set1_end_md: !input set1_end_md
  set1_days: !input set1_days
  set1_off_time: !input set1_off_time
  set1_on_time: !input set1_on_time
  set2_start_md: !input set2_start_md
  set2_end_md: !input set2_end_md
  set2_days: !input set2_days
  set2_off_time: !input set2_off_time
  set2_on_time: !input set2_on_time

  temperature_sensor: !input temperature_sensor
  temperature_unit: !input temperature_unit
  temperature_mode: !input temperature_mode
  temperature_on_threshold: !input temperature_on_threshold
  temperature_off_threshold: !input temperature_off_threshold

  today_date: "{{ now().date() }}"
  today_weekday: "{{ now().strftime('%A') }}"
  current_time: "{{ now().strftime('%H:%M') }}"

  # Parse start and end using current year and handle wrap-around logic
  set1_start_date: >-
    {{ (now().year|string) ~ '-' ~ set1_start_md }}
  set1_end_date: >-
    {{ (now().year|string) ~ '-' ~ set1_end_md }}
  set1_active: >-
    {% set today = now().date() %}
    {% set start = strptime(set1_start_date, '%Y-%m-%d').date() %}
    {% set end = strptime(set1_end_date, '%Y-%m-%d').date() %}
    {% if start <= end %}
      {{ start <= today <= end and today_weekday in set1_days }}
    {% else %}
      {{ (today >= start or today <= end) and today_weekday in set1_days }}
    {% endif %}
  in_set1_off_window: >-
    {{ set1_active and (set1_off_time <= current_time < set1_on_time) }}

  set2_start_date: >-
    {{ (now().year|string) ~ '-' ~ set2_start_md }}
  set2_end_date: >-
    {{ (now().year|string) ~ '-' ~ set2_end_md }}
  set2_active: >-
    {% set today = now().date() %}
    {% set start = strptime(set2_start_date, '%Y-%m-%d').date() %}
    {% set end = strptime(set2_end_date, '%Y-%m-%d').date() %}
    {% if start <= end %}
      {{ start <= today <= end and today_weekday in set2_days }}
    {% else %}
      {{ (today >= start or today <= end) and today_weekday in set2_days }}
    {% endif %}
  in_set2_off_window: >-
    {{ set2_active and (set2_off_time <= current_time < set2_on_time) }}

  schedule_off_window: >-
    {{ in_set1_off_window or in_set2_off_window }}

  use_temperature_control: >-
    {{ temperature_sensor is not none and temperature_sensor != '' }}

  temperature_value_raw: >-
    {% if not use_temperature_control %}
      {{ None }}
    {% else %}
      {{ states(temperature_sensor) | float(default=none) }}
    {% endif %}
  temperature_unit_sensor: >-
    {% if not use_temperature_control %}
      {{ None }}
    {% else %}
      {{ (state_attr(temperature_sensor, 'unit_of_measurement') or temperature_unit) | string }}
    {% endif %}
  current_temperature: >-
    {% if not use_temperature_control %}
      {{ None }}
    {% else %}
      {% if temperature_value_raw is string %}
        {{ None }}
      {% elif temperature_value_raw is number %}
        {% set source = temperature_unit_sensor | lower %}
        {% set target = temperature_unit | lower %}
        {% if source in ['°f','degf','f','fahrenheit'] and target in ['c','°c','degc','celsius'] %}
          {{ ((temperature_value_raw - 32) * 5 / 9) | round(2) }}
        {% elif source in ['°c','degc','c','celsius'] and target in ['f','°f','degf','fahrenheit'] %}
          {{ ((temperature_value_raw * 9 / 5) + 32) | round(2) }}
        {% else %}
          {{ temperature_value_raw }}
        {% endif %}
      {% else %}
        {{ None }}
      {% endif %}
    {% endif %}

  temp_on_condition: >-
    {% if not use_temperature_control or current_temperature is none %}
      false
    {% elif temperature_mode == 'above' %}
      {{ current_temperature >= temperature_on_threshold }}
    {% else %}
      {{ current_temperature <= temperature_on_threshold }}
    {% endif %}
  temp_off_condition: >-
    {% if not use_temperature_control or current_temperature is none %}
      false
    {% elif temperature_mode == 'above' %}
      {{ current_temperature <= temperature_off_threshold }}
    {% else %}
      {{ current_temperature >= temperature_off_threshold }}
    {% endif %}

action:
  - choose:
      - conditions:
          - condition: trigger
            id: startup
        sequence:
          - delay: "00:05:00"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ schedule_off_window }}"
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: !input outlet
              - conditions:
                  - condition: template
                    value_template: "{{ not schedule_off_window }}"
                sequence:
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ temp_on_condition }}"
                        sequence:
                          - service: switch.turn_on
                            target:
                              entity_id: !input outlet
                      - conditions:
                          - condition: template
                            value_template: "{{ temp_off_condition }}"
                        sequence:
                          - service: switch.turn_off
                            target:
                              entity_id: !input outlet
                    default:
                      - service: switch.turn_on
                        target:
                          entity_id: !input outlet

      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'set1_off' and set1_active }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input outlet

      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'set1_on' and set1_active }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ schedule_off_window }}"
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: !input outlet
              - conditions:
                  - condition: template
                    value_template: "{{ temp_on_condition }}"
                sequence:
                  - service: switch.turn_on
                    target:
                      entity_id: !input outlet
              - conditions:
                  - condition: template
                    value_template: "{{ temp_off_condition }}"
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: !input outlet
            default:
              - service: switch.turn_on
                target:
                  entity_id: !input outlet

      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'set2_off' and set2_active }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input outlet

      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'set2_on' and set2_active }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ schedule_off_window }}"
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: !input outlet
              - conditions:
                  - condition: template
                    value_template: "{{ temp_on_condition }}"
                sequence:
                  - service: switch.turn_on
                    target:
                      entity_id: !input outlet
              - conditions:
                  - condition: template
                    value_template: "{{ temp_off_condition }}"
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: !input outlet
            default:
              - service: switch.turn_on
                target:
                  entity_id: !input outlet

      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'periodic_check' }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ schedule_off_window }}"
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: !input outlet
              - conditions:
                  - condition: template
                    value_template: "{{ temp_on_condition }}"
                sequence:
                  - service: switch.turn_on
                    target:
                      entity_id: !input outlet
              - conditions:
                  - condition: template
                    value_template: "{{ temp_off_condition }}"
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: !input outlet

mode: single
